SELECT F_NAME , L_NAME FROM EMPLOYEES
 WHERE ADDRESS LIKE '%Elgin,IL%';
 
 SELECT F_NAME , L_NAME FROM EMPLOYEES
 WHERE B_DATE LIKE '197%';
 
 SELECT * FROM EMPLOYEES
 WHERE (SALARY BETWEEN 60000 AND 70000) AND DEP_ID=5;

SELECT D.DEP_NAME,E.F_NAME,E.L_NAME
 FROM EMPLOYEES AS E ,DEPARTMENTS AS D 
WHERE E.DEP_ID = D.DEPT_ID_DEP
ORDER BY D.DEP_NAME, E.L_NAME DESC;

SELECT DEP_ID, COUNT(*) FROM EMPLOYEES
GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*), AVG(SALARY) FROM EMPLOYEES
GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES" ,
AVG(SALARY) AS "AVG_SALARY" FROM EMPLOYEES
GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES" ,
AVG(SALARY) AS "AVG_SALARY" FROM EMPLOYEES
GROUP BY DEP_ID
ORDER BY AVG_SALARY;

SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES" ,
AVG(SALARY) AS "AVG_SALARY" FROM EMPLOYEES
GROUP BY DEP_ID
HAVING COUNT(*) < 4
ORDER BY AVG_SALARY;
