-----mysql -u username -p --------
-----psql -U username -d database_name---
-----sqlite3 database_name.db-----

CREATE DATABASE database_name;

USE database_name;

SHOW databases;
SHOW TABLES;

SELECT * FROM table_name;

CREATE TABLE table_name (
    column1 datatype,
    column2 datatype,
    column3 datatype,
   ....
);

INSERT INTO table_name (column1, column2, ... )
VALUES (value1, value2, ... );

UPDATE table_name
SET column1 = value1, column2 = value2, ...
WHERE condition;

DELETE FROM table_name
WHERE condition;


ALTER TABLE table_name
ADD COLUMN column_name data_type column_constraint;

ALTER TABLE table_name
DROP COLUMN column_name;

ALTER TABLE table_name
ALTER COLUMN column_name SET DATA TYPE data_type;

ALTER TABLE table_name
RENAME COLUMN current_column_name TO new_column_name;

TRUNCATE TABLE table_name;

DROP TABLE table_name;

SELECT F_NAME, L_NAME FROM TABLE_NAME WHERE ADDRESS LIKE '%ELGIN,IL%';

SELECT F_NAME, L_NAME FROM TABLE_NAME WHERE B_DATE LIKE '197%';

SELECT * FROM TABLE_NAME WHERE (SALARY BETWEEN 50,000 AND 70,000) AND DEP_ID = 5;

SELECT F_NAME, L_NAME, DEP_ID FROM TABLE_NAME ORDER BY DEP_ID;

SELECT F_NAME, L_NAME, DEP_ID FROM TABLE_NAME ORDER BY DEP_ID DESC, L_NAME DESC;

SELECT D.DEP_NAME, E.F_NAME, E.L_NAME FROM EMPLOYEES AS E, DEPARTMENTS AS D 
WHERE E.DEP_ID = D.DEP_ID ORDER BY D.DEP_NAME, E.L_NAME DESC;

SELECT DEP_ID, COUNT(*) FROM TABLE_NAME GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*), AVG(SALARY) FROM TABLE_NAME GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY" 
FROM TABLE_NAME GROUP BY DEP_ID;

SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY" 
FROM TABLE_NAME GROUP BY DEP_ID ORDER BY AVG_SALARY;

SELECT DEP_ID, COUNT(*) AS "NUM_EMPLOYEES", AVG(SALARY) AS "AVG_SALARY" 
FROM TABLE_NAME GROUP BY DEP_ID HAVING COUNT(*) < 4 ORDER BY AVG_SALARY;

SELECT SUM(COST) FROM PETRESCUE;

SELECT SUM(COST) AS SUM_OF_COST FROM PETRESCUE;

SELECT MAX(QUANTITY) FROM PETRESCUE;

SELECT AVG(COST) FROM PETRESCUE;

SELECT AVG(COST/QUANTITY) FROM PETRESCUE WHERE ANIMAL = 'Dog';

SELECT ROUND(COST) FROM PETRESCUE;

SELECT LENGTH(ANIMAL) FROM PETRESCUE;

SELECT UCASE(ANIMAL) FROM PETRESCUE;

SELECT DISTINCT(UCASE(ANIMAL)) FROM PETRESCUE;

SELECT * FROM PETRESCUE WHERE LCASE(ANIMAL) = 'cat';

SELECT DAY(RESCUEDATE) FROM PETRESCUE WHERE ANIMAL = 'Cat';

SELECT SUM(QUANTITY) FROM PETRESCUE WHERE MONTH(RESCUEDATE) = '05';

SELECT (CURRENT_DATE - RESCUEDATE) FROM PETRESCUE;

SELECT column_name [, column_name ]
FROM table1 [, table2 ]
WHERE column_name OPERATOR
   (SELECT column_name [, column_name ]
   FROM table1 [, table2 ]
   WHERE condition);

SELECT EMP_ID, F_NAME, L_NAME, SALARY FROM EMPLOYEES 
WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES);

SELECT EMP_ID, SALARY, (SELECT MAX(SALARY) FROM EMPLOYEES) AS MAX_SALARY 
FROM EMPLOYEES;

SELECT * FROM  (SELECT EMP_ID, F_NAME, L_NAME, DEP_ID FROM EMPLOYEES) AS EMP4ALL;

SELECT column_name(s)
FROM table1, table2;

SELECT column_name(s)
FROM table1, table2
WHERE table1.column_name = table2.column_name;

SELECT * FROM EMPLOYEES WHERE JOB_ID IN (SELECT JOB_IDENT FROM JOBS);

SELECT * FROM EMPLOYEES WHERE JOB_ID IN 
(SELECT JOB_IDENT FROM JOBS WHERE JOB_TITLE = 'Jr. Designer');

SELECT * FROM JOBS WHERE JOB_IDENT IN 
(SELECT JOB_ID FROM EMPLOYEES WHERE SALARY > 70000);

SELECT * FROM JOBS WHERE JOB_IDENT IN 
(SELECT JOB_ID FROM EMPLOYEES WHERE YEAR(B_DATA) > 1976);

SELECT * FROM JOBS WHERE JOB_IDENT IN 
(SELECT JOB_ID FROM EMPLOYEES WHERE YEAR(B_DATA) > 1976 AND SEX = 'F');

---SELF JOIN ---------

SELECT * FROM EMPLOYEES, JOBS;

SELECT * FROM EMPLOYEES, JOBS WHERE EMPLOYEES.JOB_ID = JOBS.JOB_IDENT;

SELECT * FROM EMPLOYEES E, JOBS J WHERE E.JOB_ID = J.JOB_IDENT;

SELECT EMP_ID, F_NAME, L_NAME, JOB_TITLE FROM EMPLOYEES, JOBS 
WHERE E.JOB_ID = J.JOB_IDENT;

----CROSS JOIN SYNTAX----------

SELECT column_name(s)
FROM table1
CROSS JOIN table2;

-------INNER JOIN--------------
SELECT column_name(s)
FROM table1
INNER JOIN table2
ON table1.column_name = table2.column_name;
WHERE condition;

-----------LEFT OUTER JOIN----------

SELECT column_name(s)
FROM table1
LEFT OUTER JOIN table2
ON table1.column_name = table2.column_name
WHERE condition;

------------RIGHT OUTER JOIN----------

SELECT column_name(s)
FROM table1
RIGHT OUTER JOIN table2
ON table1.column_name = table2.column_name
WHERE condition;

-----------------FULL OUTER JOIN-----------

SELECT column_name(s)
FROM table1
FULL OUTER JOIN table2
ON table1.column_name = table2.column_name
WHERE condition;

----------SELF JOIN--------------------

SELECT column_name(s)
FROM table1 T1, table1 T2
WHERE condition;

SELECT E.F_NAME, E.L_NAME, JH.START_DATE FROM EMPLOYEES AS E 
INNER JOIN JOB_HISTORY AS JH ON E.EMP_ID = JH.EMPL_ID 
WHERE E.DEP_ID = '5';

SELECT E.EMP_ID, E.L_NAME, E.DEP_ID, D.DEP_NAME FROM EMPLOYEES AS E 
LEFT OUTER JOIN DEPARTMENTS AS D ON E.DEP_ID = D.DEPT_ID_DEP;

SELECT E.EMP_ID, E.L_NAME, E.DEP_ID, D.DEP_NAME FROM EMPLOYEES AS E 
FULL OUTER JOIN DEPARTMENTS AS D ON E.DEP_ID = D.DEPT_ID_DEP AND E.SEX = 'M';
